server:
  port: 8080
  error:
    include-message: always

management:
  server:
    port: 8081
  endpoint:
    health:
      probes:
        enabled: true

spring:
  datasource:
    url: ${db.cloud.url}
    username: ${db.cloud.username}
    password: ${db.cloud.password}
    hikari:
      schema: public
  flyway:
    default-schema: public
  application:
    name: application-service
  jpa:
    properties:
      hibernate.transaction.jta.platform: none
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
  task:
    scheduling:
      pool:
        size: 5

mycloud:
  security:
    public-endpoints:
      - /*
      - /assets/**
      - /rest/auth/login
      - /s/**
      - /documents/*

auth:
  clean-timer:
    schedule: "0 0 0 * * *"

canary:
  sender: "my@awae.ch"
  timer:
    web: "0 */15 * * * *"

docker:
  timer:
    dockerhub: "0 30 */6 * * *"
  dockerhub:
    web-url: "https://hub.docker.com"
    api-url: "https://hub.docker.com/v2"
    username: ${dockerhub.username}
    password: ${dockerhub.password}

email:
  timer:
    send: "0 * * * * *"

ytdl:
  data-path: /data/ytdl/data
  job-path: /data/ytdl/jobs

documents:
  clean-timer:
    schedule: "0 0 * * * *"