spring:
  jpa:
    show-sql: true

logging:
  level:
    org.springframework.jdbc.core: DEBUG

db.cloud:
  url: jdbc:postgresql://localhost:21004/postgres
  username: postgres
  password: postgres

canary:
  timer:
    web: "-"
    dockerhub: "-"

email:
  timer:
    send: "-"


email-notification:
  footer: dummy
  from: test@awae.ch
  to: andreas.waelchli@me.com

mailjet:
  api-key-public: dummy
  api-key-secret: dummy