spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      schema: audit
  flyway:
    default-schema: audit
  application:
    name: audit-service
server:
  error:
    include-message: always

audit:
  consumer-group: cg-audit-service