spring:
  webflux:
    static-path-pattern: "/**"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - StripPrefix=1
      routes:
        - id: rest-services
          predicates:
            - Path=/rest/**
          uri: lb://core-service
        # auth service
        - id: auth-service
          predicates:
            - Path=/rest/auth/**
          uri: lb://auth-service
        # audit service
        - id: audit-service
          predicates:
            - Path=/rest/audit/**
          uri: lb://audit-service
        # shortener service
        - id: shortener-service
          predicates:
            - Path=/rest/shortener/**
          uri: lb://shortener-service
        # bookkeeping service
        - id: bookkeeping-service
          predicates:
            - Path=/rest/bookkeeping/**
          uri: lb://bookkeeping-service
          # canary service
        - id: canary-service
          predicates:
            - Path=/rest/canary/**
          uri: lb://canary-service
