spring:
  datasource:
    url: ${db.cloud.url}
    username: ${db.cloud.username}
    password: ${db.cloud.password}
    hikari:
      schema: shortener
  flyway:
    default-schema: shortener
  application:
    name: shortener-service
server:
  error:
    include-message: always
mycloud:
  security:
    public-endpoints: /s/**
