spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            auth-service:
              - uri: http://localhost:8001/
            audit-service:
              - uri: http://localhost:8002/
            shortener-service:
              - uri: http://localhost:8003/
