server:
  port: 8080

management:
  server:
    port: 8081
  endpoint:
    health:
      probes:
        enabled: true

spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            core-service:
              - uri: http://core-service/

  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate

logging:
  level:
    org.apache.kafka.clients.producer.ProducerConfig: WARN
    org.apache.kafka.clients.consumer.ConsumerConfig: WARN
