spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            core-service:
              - uri: http://localhost:8001/

  jpa:
    show-sql: true

logging:
  level:
    org.apache.kafka.clients.producer.ProducerConfig: INFO
    org.apache.kafka.clients.consumer.ConsumerConfig: INFO
    org.springframework.jdbc.core: DEBUG
