spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            auth-service:
              - uri: http://auth-service/
            audit-service:
              - uri: http://audit-service/
            shortener-service:
              - uri: http://shortener-service/

  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate

paas:
  kafka:
    url: ${KAFKA_BOOTSTRAP_SERVERS}

  audit:
    kafka:
      topic: paas-audit-log