spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      schema: ${DB_SCHEMA}
  flyway:
    default-schema: ${DB_SCHEMA}
  application:
    name: shortener-service
server:
  error:
    include-message: always
paas:
  security:
    public-endpoints: /s/**
