spring:
  datasource:
    url: ${db.cloud.url}
    username: ${db.cloud.username}
    password: ${db.cloud.password}
    hikari:
      schema: core
  flyway:
    default-schema: core
  application:
    name: core-service
server:
  error:
    include-message: always

mycloud:
  security:
    public-endpoints:
      - /auth/login
      - /s/**

auth:
  clean-timer:
    schedule: "0 */5 * * * *"
    max-age: "PT4H"

canary:
  timer:
    web: "0 */15 * * * *"
    dockerhub: "0 30 */6 * * *"
  dockerhub:
    web-url: "https://hub.docker.com"
    api-url: "https://hub.docker.com/v2"
    username: ${dockerhub.username}
    password: ${dockerhub.password}