server:
  port: 8001

management:
  server:
    port: 8801

spring:
  jpa:
    show-sql: true

logging:
  level:
    org.springframework.jdbc.core: DEBUG

canary:
  timer:
    web: "*/30 * * * * *"
    dockerhub: "0 * * * * *"