spring:
  datasource:
    url: ${db.cloud.url}
    username: ${db.cloud.username}
    password: ${db.cloud.password}
    hikari:
      schema: canary
  flyway:
    default-schema: canary
  application:
    name: canary-service
server:
  error:
    include-message: always

canary:
  timer:
    web: "0 */30 * * * *"
    dockerhub: "0 30 */6 * * *"
  kafka:
    topic: telegram-notifications