spring:
  datasource:
    url: ${db.cloud.url}
    username: ${db.cloud.username}
    password: ${db.cloud.password}
    hikari:
      schema: canary
  flyway:
    default-schema: canary
  application:
    name: canary-service
server:
  error:
    include-message: always

canary:
  timer:
    web: "0 */15 * * * *"
    dockerhub: "0 30 */6 * * *"

  dockerhub:
    web-url: "https://hub.docker.com"
    api-url: "https://hub.docker.com/v2"
    username: ${dockerhub.username}
    password: ${dockerhub.password}