server:
  port: 8080

management:
  server:
    port: 8081
  endpoint:
    health:
      probes:
        enabled: true

spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            auth-service:
              - uri: http://auth-service/
            audit-service:
              - uri: http://audit-service/
            shortener-service:
              - uri: http://shortener-service/
            canary-service:
              - uri: http://canary-service/

  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate

mycloud:
  audit:
    kafka:
      topic: mycloud-audit-log

logging:
  level:
    org.apache.kafka.clients.producer.ProducerConfig: WARN
    org.apache.kafka.clients.consumer.ConsumerConfig: WARN
