spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            auth-service:
              - uri: http://localhost:8001/
            audit-service:
              - uri: http://localhost:8002/
            shortener-service:
              - uri: http://localhost:8003/
            bookkeeping-service:
              - uri: http://localhost:8004/
            canary-service:
              - uri: http://localhost:8005/

  jpa:
    show-sql: true

logging:
  level:
    org.apache.kafka.clients.producer.ProducerConfig: INFO
    org.apache.kafka.clients.consumer.ConsumerConfig: INFO
    org.springframework.jdbc.core: DEBUG
